### ISSUE TITLE
[Feature request]Ability to set features for chocolatey via variables

### ISSUE THREAD

**Issue by marcinbojko** [chocolatey/puppet-chocolatey#139]
It would be really nice to allow set features globally with puppet/Foreman variables.

**Comment by ferventcoder** [comment]
How about 

~~~puppet
chocolateyfeature {'featureName':
  ensure => 'enabled',
}
~~~

**Comment by ferventcoder** [comment]
This is available right now - https://forge.puppet.com/puppetlabs/chocolatey#chocolateyfeature

**Comment by marcinbojko** [comment]
Gladly, I see your point. But I was thinking rather about parameters part. As for now, if you want to use choco with foreman you have to write your own class to use: chocolateyfeature class.
I was thinking about creating extra parameters like: chocofeatures, and passing it IN puppet/chocolatey class like:
chocofeatures:
  feature1: 0
  feature2: 1

and so on.

**Comment by marcinbojko** [comment]
I don't know If I missed something, but I am using: https://forge.puppet.com/chocolatey/chocolatey

**Comment by ferventcoder** [comment]
@marcinbojko I'm not sure I understand the purpose of parameters versus types and providers. Is there some benefit to using parameters over using T&P like chocolateyfeature? Don't forget that you can always use install_options to pass parameters.

Also, you probably missed something 👍 . https://puppet.com/blog/package-management-windows-gets-even-better-chocolatey

**Comment by marcinbojko** [comment]
Yeah, I know about OneGet.
My point is: if you want to user chocofeatures, you have to write your own class/module.
Using parameters you can pass the resources to the module.

**Comment by ferventcoder** [comment]
> Yeah, I know about OneGet.

Where was OneGet mentioned?

**Comment by ferventcoder** [comment]
Let's not confuse "package management" with "PowerShell PackageManagement" - note the proper name of the second, which is a package management aggregator.

**Comment by ferventcoder** [comment]
> My point is: if you want to user chocofeatures, you have to write your own class/module.
> Using parameters you can pass the resources to the module.

Perhaps you can explain this to me some more? Not trying to be daft, I'm just not understanding why you wouldn't just use the module. If it because the Foreman provides a default module you can plug into with your ENC variables, then I would suggest that be a feature of that module.

I mean you can't get away from having to write:

~~~puppet
package{'name/hiera var':
  ensure => 'installed/latest/version/absent/hiera var',
}
~~~

It may be that the Foreman has a default module already available for you where it was written. So it seems that parameters is a feature request for them, unless I'm mistaken. cc @genebean

**Comment by marcinbojko** [comment]
@ferventcoder. My first error is that I don't understand difference between chocolatey/chocolatey module and puppetlabs/chocolatey module. I suppose the latter has the ability to manage features the former hasn't.
So, let me check if I just replace modules, managing features will be available.
PS. I would never get you as a daft one ;)

**Comment by marcinbojko** [comment]
Ok, no changes at all.
So, why parameters? Foreman allows you to change only parameters declared in params.pp. Other params not declared are just not visible.
And if I want to change chocofeature I should write another wrapper module to:
- declare param like 'resources' 
- execute create_resources(chocolatey::chocofeature,$resources)

**Comment by ferventcoder** [comment]
Yes, the latter has `chocolateysource`, `chocolateyfeature`, and `chocolateyconfig`.

**Comment by ferventcoder** [comment]
Ah, those kind of parameters. The problem with params typically is that it applies to classes and defined types, where things like `package` are a type and you would need a defined type to pass params to. That's typically why I stated you would still need to define a package resource somewhere. The new types and providers fall into that same category.

IIRC, the Foreman has some additional variables it can declare and use that take advantage of ENC/hiera as well.

**Comment by marcinbojko** [comment]
You just can change values defined in params. 
So simple $chocofeature  param (type undefined) will be fine ;)

**Comment by vandelin586** [comment]
I'm not sure this is the proper place for this , I am having the following issue with the install of chocolatey
"When FIPS Mode is enabled, Chocolatey requires useFipsCompliantChecksums feature also be enabled."
Chocolatey won't install via puppet, it looks as if this is the reason, the Eny does have FIPS turned on and wont be turning it off anytime soon . May I pass the following parameter in somewhere during or before the chocolatey install

Thank you

**Comment by marcinbojko** [comment]
Sadly, I wrote that part it myself.

**Comment by vandelin586** [comment]
I'm guessing that response is to mine? You wrote that function into this code yourself is what your saying?

Forgive me, im pretty new, but either I need to use another chocolatey code module from the forge or know how to include this function into this module.... Do I have my thinking correct?

**Comment by marcinbojko** [comment]
@vandelin586 @ferventcoder pointed that featured code is already in puppetlabs-chocolatey module. Sadly, I was using chocolatey-chocolatey module, where those features were still unavailable.
So I wrote that piece myself, in whole aggregated unit called win_manage.

I hope, I will be able to release tested version soon: https://marcinbojko.wordpress.com/2016/10/04/puppet-the-foreman-powershell-dsc-your-system-center-in-a-box/
I am newbie in coding also, so far I am SysAdmin/Network engineer, but small steps at a time ;)

**Comment by ferventcoder** [comment]
This? https://forge.puppet.com/puppetlabs/chocolatey#enable-fips-compliant-checksums

``` puppet
chocolateyfeature {'usefipscompliantchecksums':
  ensure => enabled,
}
```

However I hear that something is causing issues prior to even being installable? I'd like to dig in a little more @vandelin586 - can you reach out in a new issue here, over at chocolatey/choco repository, or in the [Puppet #windows slack channel](http://slack.puppet.com/)?

**Comment by vandelin586** [comment]
So with the puppet implementation that choco is failing on. This is on a network I do not yet have access to. I cant see the code, yet. I was just going off hear say by others.

In my test lab , I stood up win 2012 , tried my test lab chco puppet install = sucess 
In my test lab , I stood up win 2012 ,enabled fips, tried my test lab chco puppet install = fail
In my test lab , I stood up win 2012 ,enabled fips,ran 
chocolateyfeature {'usefipscompliantchecksums':
  ensure => enabled,
}, tried my test lab chco puppet install = sucess 

The network I dont yet have access to , they are using chocolatey\chocolatey.

I dont think chco is fully installed as the server wont respond to choco.exe commands . Their puppet code is to use choco but it might be failing because of something like below?

running in elevated cmd window
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

on the server comes back as cannot connect, connection dropped bad ssl handshake type errors

This client is mandated to use FIPS and have very strict firewall / security policies/rules I dont think anything is wrong with the code / puppet code / modules that i have seen so far

**Comment by vandelin586** [comment]
when i say chco install , the way the client has this particular piece of code. Its an all in one, install choco and use choco in the same module to install windows features and such , as iis. my request is in to get read access to their code , tue or wed i should have access. I want to see if i can re design some of this

**Comment by ferventcoder** [comment]
As I mentioned, please create a new issue as I'd like to keep as much of the conversation there as possible. Once you've created the new issue, I will discuss more about things I'd like to understand.

**Comment by marcinbojko** [comment]
@ferventcoder - Since this functionality is embedded in puppetlabs module, can I close this issue?

**Comment by vandelin586** [comment]
I have never opened one before, but i will give it my best coach ! TY

**Comment by ferventcoder** [comment]
@vandelin586  there is a link at the top for "New Issue" - I'm sure you will do fine. 👍 

@marcinbojko sure, we can close this.
