### ISSUE TITLE
How I overcame SSL handshake issues

### ISSUE THREAD

**Issue by vandelin586** [chocolatey/puppet-chocolatey#148]
I brought this issue up  about a month ago....

I really didn't want to open an issue for something I knew the owners had functionality to make it work.

I just want to explain the issue and how we overcame the issue at least for the time being.

We wanted Puppet to install chocolatey , so we setup our environment to pull this chocolatey module and install it on the clients. Thing was that it was not working, after some research I found that by default chocolatey reaches out to the vendor website, downloads chocolatey package, and then install it ..

This company IT policies prevented the SSL handshake from happening, it was not considered trusted. In order to meet our deadline to the stakeholders, we don't want to go through the process at this time to make chocolatey.org an exception and wait for the business to add it as a trusted repo, assuming they even would....

I downloaded the .nupkg file , scanned it, and placed it in the company's own repo. Thus SSL trust is already established..

In my profile for chocolatey I said 
class {'chocolatey':
    chocolatey_download_url  => 'company private repo url pointting right to .nupkg file',
  }

The chocolate class accepts the chocolatey_download_url parameter to over ride the default

Anyway , Long story to explain something simple im sure....
But thats what I did to get past having to make an SSL connection to chocolatey website.

**Comment by ferventcoder** [comment]
@vandelin586 For the install of Chocolatey itself, we're adding newer TLS versions automatically when supported by your environment - https://github.com/puppetlabs/puppetlabs-chocolatey/commit/4e31ed77d200d393d29e1a054563c8690d671dc2

**Comment by ferventcoder** [comment]
updated prior message.

**Comment by ferventcoder** [comment]
@vandelin586 I'd like to clear up a possible misconception here.

> Thing was that it was not working, after some research I found that by default chocolatey reaches out to the vendor website, downloads chocolatey package, and then install it ..

I think you are saying that a package on the community repository (https://chocolatey.org/packages) is downloaded by Chocolatey, and the package scripts from that community package will reach out to download software from the vendor website and install it. This is due to [redistribution rights and copyright law (for the software that the package represents)](https://chocolatey.org/docs/community-packages-disclaimer) in many instances since the site is public. 

It does require an understanding that [Chocolatey != Chocolatey.org packages](https://chocolatey.org/blog/host-your-own-server). Chocolatey is completely decentralized as you have noted in saying you download the Chocolatey nupkg and host it on your own internal repository.

Typically organizations using Chocolatey will come to the community repository for two reasons, to grab a version or the latest version of the Chocolatey nupkg and put it on their internal server, and the second time is when they want to use an existing package on the community site but without the hit to the internet. So they do a process called internalization - https://chocolatey.org/docs/how-to-recompile-packages. Chocolatey for Business has [Package Internalizer](https://chocolatey.org/docs/features-automatically-recompile-packages), which will do the internalization for you automatically.

**Comment by vandelin586** [comment]
Thank you for the clarification and for the updates on "adding newer TLS versions automatically"

I look forward to the new updates and I will look into chocolatey for business and discuss with the team those options as well.
