### ISSUE TITLE
Choose version of chocolatey to install

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/puppet-chocolatey#80]

**Comment by andreguilhon** [comment]
In the README of the module it says one can use the chocolatey_version as a class parameter. I tried using it, since I need an specific version (since it requires a checksum for unsecure fonts), but had no luck using it. It says that chocolatey_version is an invalid parameter for the class.
Any other way to achieve this?

**Comment by andreguilhon** [comment]
Had an outdated version of the class, after upgrading it to the current version, it does not complain anymore about the parameter, but it simply ignores it! :(

**Comment by andreguilhon** [comment]
Setting the chocolatey_download_url => 'https://packages.chocolatey.org/chocolatey.0.9.9.12.nupkg' did the trick for me!

**Comment by ferventcoder** [comment]
@andreguilhon The `chocolatey_version` is almost not worth having. It doesn't do what you might think, it only allows you to tell the module what version you are installing, but it's just information, not a directive of what to install.

**Comment by ferventcoder** [comment]
This issue was resolved quite awhile ago though.

**Comment by ferventcoder** [comment]
You may want to seek out https://forge.puppetlabs.com/puppetlabs/chocolatey as it has `chocolateyfeature`, which will allow you to shut this feature off when you are using it internally.
